<a href="https://colab.research.google.com/github/Shriansh16/ML_Revision/blob/main/productivity_timeseries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/content/AssignmentData.xlsx - WorkerFunnel.csv')

In [3]:
df.head()

,Date,Quarter,Department,Targeted Productivity,Overtime,No. of Workers,Actual Productivity
0,1/1/2015,Q1,Sewing,0.80,7080,59.0,0.940725
1,1/1/2015,Q1,Finishing,0.75,960,8.0,0.886500
2,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
3,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
4,1/1/2015,Q1,Sewing,0.80,1920,56.0,NaN

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   1197 non-null   object
 1   Quarter                1197 non-null   object
 2   Department             1197 non-null   object
 3   Targeted Productivity  1197 non-null   float64
 4   Overtime               1197 non-null   int64
 5   No. of Workers         1197 non-null   float64
 6   Actual Productivity    1197 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 65.6+ KB

#DATA CLEANING

In [4]:
df.shape

(1197, 7)

In [5]:
df.isnull().sum()

Date                      0
Quarter                   0
Department                0
Targeted Productivity     0
Overtime                  0
No. of Workers            0
Actual Productivity      30
dtype: int64

####HANDLING THE MISSING VALUES OF 'Actual Productivity'

In [6]:
df['Quarter'].value_counts()

Q1    360
Q2    335
Q4    248
Q3    210
Q5     44
Name: Quarter, dtype: int64

HANDLING MISSING VALUES OF 'Actual Productivity' QUARTER WISE

####QUARTER 1

In [7]:
df[df['Quarter']=='Q1'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      9
dtype: int64

In [8]:
df[df['Quarter']=='Q1']['Actual Productivity'].median()

0.800034503

filling the missing values of 'Actual Productivity' with the median of 'Actual Productivity' in Quarter 1

In [9]:
median1=df[df['Quarter']=='Q1']['Actual Productivity'].median()

In [10]:
median1

0.800034503

In [11]:
df[df['Quarter']=='Q1']=df[df['Quarter']=='Q1'].fillna(median1)

In [12]:
df[df['Quarter']=='Q1']

,Date,Quarter,Department,Targeted Productivity,Overtime,No. of Workers,Actual Productivity
0,1/1/2015,Q1,Sewing,0.80,7080,59.0,0.940725
1,1/1/2015,Q1,Finishing,0.75,960,8.0,0.886500
2,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
3,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
4,1/1/2015,Q1,Sewing,0.80,1920,56.0,0.800035
...,...,...,...,...,...,...,...
1101,7/3/2015,Q1,Sewing,0.65,4200,45.0,0.650240
1102,7/3/2015,Q1,Finishing,0.80,3600,15.0,0.590741
1103,7/3/2015,Q1,Finishing,0.65,1920,8.0,0.528125
1104,7/3/2015,Q1,Sewing,0.50,2280,39.0,0.500528
1105,7/3/2015,Q1,Sewing,0.70,6960,58.0,0.408960

In [13]:
df[df['Quarter']=='Q1'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      0
dtype: int64

In [14]:
df.isnull().sum()

Date                      0
Quarter                   0
Department                0
Targeted Productivity     0
Overtime                  0
No. of Workers            0
Actual Productivity      21
dtype: int64

####QUARTER 2

In [15]:
df[df['Quarter']=='Q2'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      8
dtype: int64

In [16]:
median2=df[df['Quarter']=='Q2']['Actual Productivity'].median()

In [17]:
median2

0.800034503

filling the missing values of 'Actual Productivity' with the median of 'Actual Productivity' in Quarter 2

In [18]:
df[df['Quarter']=='Q2']=df[df['Quarter']=='Q2'].fillna(median2)

In [19]:
df[df['Quarter']=='Q2'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      0
dtype: int64

In [20]:
df.isnull().sum()

Date                      0
Quarter                   0
Department                0
Targeted Productivity     0
Overtime                  0
No. of Workers            0
Actual Productivity      13
dtype: int64

####QUARTER 3

In [21]:
df[df['Quarter']=='Q3'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      5
dtype: int64

In [22]:
median3=df[df['Quarter']=='Q3']['Actual Productivity'].median()

In [23]:
median3

0.72830303

filling the missing values of 'Actual Productivity' with the median of 'Actual Productivity' in Quarter 3

In [24]:
df[df['Quarter']=='Q3']=df[df['Quarter']=='Q3'].fillna(median3)

In [25]:
df[df['Quarter']=='Q3'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      0
dtype: int64

In [26]:
df.isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      8
dtype: int64

####QUARTER 4

In [27]:
df[df['Quarter']=='Q4'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      7
dtype: int64

In [28]:
median4=df[df['Quarter']=='Q4']['Actual Productivity'].median()

In [29]:
median4

0.750371895

filling the missing values of 'Actual Productivity' with the median of 'Actual Productivity' in Quarter 4

In [30]:
df[df['Quarter']=='Q4']=df[df['Quarter']=='Q4'].fillna(median4)

In [31]:
df[df['Quarter']=='Q4'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      0
dtype: int64

In [32]:
df.isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      1
dtype: int64

####QUARTER 5

In [33]:
df[df['Quarter']=='Q5'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      1
dtype: int64

In [35]:
median5=df[df['Quarter']=='Q5']['Actual Productivity'].median()

In [36]:
median5

0.877552083

filling the missing values of 'Actual Productivity' with the median of 'Actual Productivity' in Quarter 5

In [37]:
df[df['Quarter']=='Q5']=df[df['Quarter']=='Q5'].fillna(median5)

In [38]:
df[df['Quarter']=='Q5'].isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      0
dtype: int64

In [39]:
df.isnull().sum()

Date                     0
Quarter                  0
Department               0
Targeted Productivity    0
Overtime                 0
No. of Workers           0
Actual Productivity      0
dtype: int64

####All the missing values are handled

In [40]:
df.head()

,Date,Quarter,Department,Targeted Productivity,Overtime,No. of Workers,Actual Productivity
0,1/1/2015,Q1,Sewing,0.80,7080,59.0,0.940725
1,1/1/2015,Q1,Finishing,0.75,960,8.0,0.886500
2,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
3,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
4,1/1/2015,Q1,Sewing,0.80,1920,56.0,0.800035

In [41]:
df

,Date,Quarter,Department,Targeted Productivity,Overtime,No. of Workers,Actual Productivity
0,1/1/2015,Q1,Sewing,0.80,7080,59.0,0.940725
1,1/1/2015,Q1,Finishing,0.75,960,8.0,0.886500
2,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
3,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
4,1/1/2015,Q1,Sewing,0.80,1920,56.0,0.800035
...,...,...,...,...,...,...,...
1192,11/3/2015,Q2,Finishing,0.75,960,8.0,0.628333
1193,11/3/2015,Q2,Finishing,0.70,960,8.0,0.800035
1194,11/3/2015,Q2,Finishing,0.65,960,8.0,0.625625
1195,11/3/2015,Q2,Finishing,0.75,1800,15.0,0.505889
1196,11/3/2015,Q2,Finishing,0.70,720,6.0,0.394722

In [45]:
df_sewing=df[df['Department']=='Sewing']
df_finishing=df[df['Department']=='Finishing']

In [49]:
df_sewing.reset_index(inplace=True,drop=True)

In [53]:
df_sewing.drop('index',axis=1,inplace=True)

<ipython-input-53-49dc963dd89f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sewing.drop('index',axis=1,inplace=True)

In [54]:
df_sewing

,Date,Quarter,Department,Targeted Productivity,Overtime,No. of Workers,Actual Productivity
0,1/1/2015,Q1,Sewing,0.80,7080,59.0,0.940725
1,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
2,1/1/2015,Q1,Sewing,0.80,3660,30.5,0.800570
3,1/1/2015,Q1,Sewing,0.80,1920,56.0,0.800035
4,1/1/2015,Q1,Sewing,0.80,6720,56.0,0.800125
...,...,...,...,...,...,...,...
686,11/3/2015,Q2,Sewing,0.75,7080,59.0,0.800035
687,11/3/2015,Q2,Sewing,0.70,6960,58.0,0.700557
688,11/3/2015,Q2,Sewing,0.70,6840,57.0,0.700505
689,11/3/2015,Q2,Sewing,0.70,4560,38.0,0.700246
690,11/3/2015,Q2,Sewing,0.65,6840,57.0,0.650596

In [59]:
df = df.groupby(['Date', 'Quarter', 'Department']).agg({
    'Targeted Productivity': 'mean',
    'Overtime': 'sum',
    'No. of Workers': 'sum',
    'Actual Productivity': 'mean'
}).reset_index()

In [60]:
df

,Date,Quarter,Department,Targeted Productivity,Overtime,No. of Workers,Actual Productivity
0,1/1/2015,Q1,Finishing,0.735714,8400,70.0,0.708296
1,1/1/2015,Q1,Sewing,0.762500,67080,604.0,0.755066
2,1/13/2015,Q2,Finishing,0.740000,19260,91.0,0.815529
3,1/13/2015,Q2,Sewing,0.720833,113760,632.0,0.705597
4,1/14/2015,Q2,Finishing,0.740000,15840,85.0,0.736257
...,...,...,...,...,...,...,...
113,8/3/2015,Q2,Sewing,0.704545,57420,564.0,0.723055
114,9/2/2015,Q2,Finishing,0.716667,8160,68.0,0.764154
115,9/2/2015,Q2,Sewing,0.700000,48840,638.0,0.721392
116,9/3/2015,Q2,Finishing,0.730000,0,98.0,0.737816
117,9/3/2015,Q2,Sewing,0.704167,69540,622.0,0.721293

In [61]:
df_sewing=df[df['Department']=='Sewing']

In [62]:
df_sewing

,Date,Quarter,Department,Targeted Productivity,Overtime,No. of Workers,Actual Productivity
1,1/1/2015,Q1,Sewing,0.762500,67080,604.0,0.755066
3,1/13/2015,Q2,Sewing,0.720833,113760,632.0,0.705597
5,1/14/2015,Q2,Sewing,0.704545,77490,577.5,0.678468
7,1/15/2015,Q3,Sewing,0.687500,110850,630.5,0.703352
9,1/17/2015,Q3,Sewing,0.720833,109890,630.5,0.714543
11,1/18/2015,Q3,Sewing,0.729167,106800,632.0,0.684814
13,1/19/2015,Q3,Sewing,0.683333,104400,635.0,0.683872
15,1/2/2015,Q1,Sewing,0.740909,62340,578.5,0.757486
17,1/20/2015,Q3,Sewing,0.677273,99750,577.5,0.700142
19,1/21/2015,Q3,Sewing,0.700000,105690,691.5,0.733436
21,1/22/2015,Q4,Sewing,0.691667,118710,635.5,0.700671
23,1/24/2015,Q4,Sewing,0.691667,109770,631.5,0.733697
25,1/25/2015,Q4,Sewing,0.708333,105660,635.0,0.737111
27,1/26/2015,Q4,Sewing,0.695455,94470,575.5,0.722947
29,1/27/2015,Q4,Sewing,0.700000,62700,572.5,0.731406
31,1/28/2015,Q4,Sewing,0.679167,72180,628.5,0.707885
33,1/29/2015,Q5,Sewing,0.709091,67380,576.5,0.781058
35,1/3/2015,Q1,Sewing,0.716667,62160,628.0,0.712992
37,1/31/2015,Q5,Sewing,0.716667,74700,634.5,0.738043
39,10/1/2015,Q2,Sewing,0.745833,107400,632.0,0.763769
41,10/2/2015,Q2,Sewing,0.733333,39840,639.0,0.754128
43,10/3/2015,Q2,Sewing,0.729167,70380,626.0,0.752742
45,11/1/2015,Q2,Sewing,0.766667,108180,633.0,0.739009
47,11/2/2015,Q2,Sewing,0.716667,42120,640.5,0.755212
49,11/3/2015,Q2,Sewing,0.741667,70260,625.0,0.746133
51,12/1/2015,Q2,Sewing,0.737500,102030,629.5,0.745087
53,12/2/2015,Q2,Sewing,0.700000,58560,638.5,0.677099
55,2/14/2015,Q2,Sewing,0.720000,54540,533.0,0.706250
57,2/15/2015,Q3,Sewing,0.713636,61380,584.5,0.643075
59,2/16/2015,Q3,Sewing,0.713636,42660,569.0,0.679870
61,2/17/2015,Q3,Sewing,0.700000,51900,628.0,0.694890
63,2/18/2015,Q3,Sewing,0.729167,39720,626.0,0.650729
65,2/19/2015,Q3,Sewing,0.737500,51900,630.0,0.678128
67,2/2/2015,Q1,Sewing,0.733333,74820,635.5,0.713303
69,2/22/2015,Q4,Sewing,0.740909,61080,581.0,0.621448
71,2/23/2015,Q4,Sewing,0.740909,60060,574.0,0.706653
73,2/24/2015,Q4,Sewing,0.733333,56040,626.0,0.682802
75,2/25/2015,Q4,Sewing,0.745833,59160,621.0,0.741982
77,2/26/2015,Q4,Sewing,0.691667,65100,631.0,0.674212
79,2/28/2015,Q4,Sewing,0.691667,53060,632.0,0.700389
81,2/3/2015,Q1,Sewing,0.736364,55740,570.0,0.764047
83,3/1/2015,Q1,Sewing,0.775000,88380,628.5,0.778330
85,3/2/2015,Q1,Sewing,0.745833,72000,635.0,0.766277
87,3/3/2015,Q1,Sewing,0.720833,65400,617.0,0.767054
89,4/1/2015,Q1,Sewing,0.775000,79770,628.5,0.786353
91,4/2/2015,Q1,Sewing,0.716667,73560,635.0,0.779525
93,4/3/2015,Q1,Sewing,0.733333,64080,621.0,0.681014
95,5/1/2015,Q1,Sewing,0.775000,81300,636.5,0.779485
97,5/2/2015,Q1,Sewing,0.685000,67320,604.0,0.757002
99,5/3/2015,Q1,Sewing,0.700000,47700,568.0,0.662130
101,6/1/2015,Q1,Sewing,0.779167,112830,635.5,0.787794
103,7/1/2015,Q1,Sewing,0.787500,113490,634.5,0.772160
105,7/2/2015,Q1,Sewing,0.750000,71160,611.0,0.743730
107,7/3/2015,Q1,Sewing,0.710000,52380,508.0,0.711206
109,8/1/2015,Q2,Sewing,0.750000,148530,634.5,0.740439
111,8/2/2015,Q2,Sewing,0.754167,71760,608.0,0.731646
113,8/3/2015,Q2,Sewing,0.704545,57420,564.0,0.723055
115,9/2/2015,Q2,Sewing,0.700000,48840,638.0,0.721392
117,9/3/2015,Q2,Sewing,0.704167,69540,622.0,0.721293